/**
 * Per-range descriptive copy, keyed by group slug.
 *
 * Round 2 of the audit: product pages carry ~32 words of unique copy —
 * mostly a templated sentence ("Landau PLA Pro 1.75mm 1kg — premium 3D
 * printer filament") — which tells a buyer nothing about why PLA Pro
 * costs £10 and PLA Basic costs £6, and gives Google nothing
 * distinguishing to rank.
 *
 * The audit's own suggestion was to adapt the range-comparison
 * paragraphs already written for the material category pages, which is
 * what this is: the same judgements, expanded per range and written to
 * stand on their own rather than as one clause in a list.
 *
 * Structured as data rather than markdown in the database on purpose.
 * The description columns are regenerated by the seed script, so copy
 * living there is copy that can be silently overwritten; this is
 * versioned, reviewable, and diffable.
 *
 * `bestFor` / `notFor` is the honest pairing the brand voice already
 * uses elsewhere — the "what it's bad at" line is the one most likely to
 * stop a wrong purchase, which is worth more than the sale it costs.
 */

export interface RangeCopy {
  /** One-line positioning, shown under the H1. */
  summary: string;
  /** Two or three paragraphs of real detail. */
  body: string[];
  bestFor: string[];
  notFor: string[];
  /** Material slug for the "more about this material" link. */
  material: string;
}

export const RANGE_COPY: Record<string, RangeCopy> = {
  'landau-pla-1-75mm-1kg': {
    material: 'pla',
    summary: 'The standard PLA. The cheapest way to print a lot of parts that do not need to survive heat.',
    body: [
      'This is the baseline range and the one to reach for when the job is a prototype, a display piece, a jig, or anything else that lives indoors and never gets hot. It prints at 200–220 °C with no enclosure, warps so little that large flat parts are realistic on an open-frame printer, and is more dimensionally accurate than anything else we stock.',
      'If you are commissioning a new printer, start here. When a print fails in standard PLA the cause is almost always the machine rather than the filament, which makes it the right material to tune against.',
    ],
    bestFor: ['Prototypes and test fits', 'Display and decorative prints', 'Indoor enclosures and jigs'],
    notFor: ['Anything above ~55 °C', 'Load-bearing parts (it creeps)', 'Outdoor use'],
  },
  'landau-pla-basic-1-75mm-1kg': {
    material: 'pla',
    summary: 'Standard PLA with tighter batch-to-batch colour consistency.',
    body: [
      'Mechanically this behaves like our standard PLA — same temperatures, same forgiving print, same limits on heat and load. What you are paying for is consistency: colour matched more closely between batches, so a part printed in March matches one printed in September.',
      'That matters for multi-part assemblies printed over time, and for anything customer-facing where two halves in visibly different greys would be obvious. For a one-off print where nothing has to match, standard PLA does the same job for less.',
    ],
    bestFor: ['Multi-part assemblies printed over time', 'Repeat production runs', 'Anything colour-matched'],
    notFor: ['One-off prints where colour matching is irrelevant', 'Heat or load-bearing use'],
  },
  'landau-pla-pro-1-75mm-1kg': {
    material: 'pla',
    summary: 'Toughened PLA — noticeably less brittle, for functional parts that are still not hot.',
    body: [
      'PLA Pro is formulated to absorb impact rather than shatter. Standard PLA is stiff but brittle: it snaps cleanly when dropped or flexed. Pro bends further before it fails, which is the difference between a clip that survives being pushed on and off and one that breaks on the third go.',
      'It prints at much the same settings as standard PLA, so there is no new tuning to do. The heat limit is unchanged — this is toughness, not heat resistance. If the part will get warm, you want PETG rather than a better PLA.',
    ],
    bestFor: ['Clips, catches and snap fits', 'Parts that get handled or dropped', 'Functional prints at room temperature'],
    notFor: ['Anything warm — the heat limit is the same as standard PLA', 'Sustained load over months'],
  },
  'landau-pla-matte-1-75mm-1kg': {
    material: 'pla',
    summary: 'A diffuse, non-reflective finish that hides layer lines remarkably well.',
    body: [
      'Matte PLA trades a little strength for a surface that scatters light instead of reflecting it, which makes layer lines far less visible without any post-processing. On a display piece it is the difference between "3D printed" and "moulded" at arm\'s length.',
      'Treat the finish as the point. It is slightly more brittle than standard PLA and no more heat-resistant, so it belongs on things that are looked at rather than used.',
    ],
    bestFor: ['Display models and props', 'Photographed or filmed pieces', 'Anywhere layer lines would spoil it'],
    notFor: ['Functional or load-bearing parts', 'Anything that needs impact resistance'],
  },
  'landau-pla-silk-1-75mm-1kg': {
    material: 'pla',
    summary: 'High-gloss, near-metallic sheen. Prints best slightly hotter and slower.',
    body: [
      'Silk PLA has a lustrous, almost liquid finish that reads as metal or polished plastic under direct light. It is the most decorative material we stock and by some distance the most photogenic.',
      'It rewards patience: run 5–10 °C hotter than standard PLA and slow down, particularly on outer walls, or the sheen breaks up. Mechanically it is weaker than standard PLA — the additives that produce the gloss come at the cost of layer adhesion — so keep it for things that are displayed rather than used.',
    ],
    bestFor: ['Decorative and gift pieces', 'Vases and single-wall prints', 'Anything where finish beats strength'],
    notFor: ['Functional parts — layer adhesion is weaker', 'Fast printing; it needs slowing down'],
  },
  'landau-pla-hyper-1-75mm-1kg': {
    material: 'pla',
    summary: 'Formulated for high-speed printers. Wasted on a slow one.',
    body: [
      'Hyper PLA is engineered to melt and flow fast enough to keep up with machines that can genuinely move — the current generation of CoreXY and high-flow hot ends. At flow rates where standard PLA begins to under-extrude and lose surface quality, this keeps a clean wall.',
      'Be honest about the printer before paying the premium. On a machine that tops out at 60 mm/s, Hyper PLA behaves like good standard PLA and the extra cost buys nothing.',
    ],
    bestFor: ['High-flow hot ends and CoreXY machines', 'Large prints where time is the constraint', 'Batch production'],
    notFor: ['Slower printers — the premium buys nothing', 'Anything needing heat resistance'],
  },
  'landau-pla-carbon-fibre-1-75mm-1kg': {
    material: 'pla',
    summary: 'Stiffer and matte, with a chopped-fibre filler. Needs a hardened nozzle.',
    body: [
      'Carbon fibre PLA is noticeably stiffer than plain PLA and resists creep — the slow deformation under constant load that makes standard PLA a poor choice for brackets. It also prints with a handsome, grainy matte finish that hides layer lines.',
      'Two things to know before buying. It is abrasive and will chew through a brass nozzle in a few hundred hours, so a hardened steel nozzle is not optional. And stiffer is not stronger: it is more brittle than plain PLA, so it fails suddenly rather than bending. Choose it when rigidity matters more than impact resistance.',
    ],
    bestFor: ['Brackets and jigs that must not flex', 'Parts that would creep in plain PLA', 'Matte structural pieces'],
    notFor: ['Printers with a brass nozzle', 'Anything that takes impact — it is more brittle, not less'],
  },
  'landau-petg-1-75mm-1kg': {
    material: 'petg',
    summary: 'The functional default. Tougher than PLA, warmer-rated, and water-tight.',
    body: [
      'PETG is the material for parts that have to do a job rather than look like one. It handles roughly 75–80 °C — a car interior in summer, the inside of most electronics enclosures — and it bends measurably before it fails where PLA simply snaps.',
      'Layer adhesion is excellent, which is what makes it water-tight: a PETG print with enough walls will genuinely hold liquid where the same part in PLA weeps through the layer boundaries.',
      'The trade-off is a fussier print. Run cooling at 30–50%, not 100%, and dry the filament if it has been open more than a few weeks — wet PETG is the single most common cause of "my PETG is stringy".',
    ],
    bestFor: ['Brackets and functional parts', 'Water-tight containers', 'Anything that lives somewhere warm'],
    notFor: ['Fine detail and miniatures — it oozes and rounds corners', 'Steep unsupported overhangs'],
  },
  'landau-petg-pro-1-75mm-1kg': {
    material: 'petg',
    summary: 'PETG with tighter diameter consistency and a cleaner surface.',
    body: [
      'Same mechanical properties as our standard PETG — same heat rating, same toughness, same water-tightness — with tighter diameter tolerance through the spool. That shows up as more even extrusion, which is most visible on large flat faces and on the first layer.',
      'If your PETG prints are already coming out clean, standard PETG is the sensible buy. If you are fighting inconsistent extrusion on wide surfaces, this is the range that removes filament diameter from the list of suspects.',
    ],
    bestFor: ['Large flat surfaces where banding shows', 'Precision fits', 'Long unattended prints'],
    notFor: ['Casual prints where standard PETG is already fine'],
  },
  'landau-petg-hyper-1-75mm-1kg': {
    material: 'petg',
    summary: 'PETG tuned for high-speed machines.',
    body: [
      'The same idea as Hyper PLA, applied to a harder material to print. High-flow PETG keeps layer adhesion and surface quality at speeds where standard PETG starts to under-extrude and string.',
      'As with Hyper PLA, this only pays off on a printer that can use it. On a slower machine it prints like good standard PETG.',
    ],
    bestFor: ['High-flow hot ends', 'Large functional prints against the clock'],
    notFor: ['Slower printers — no benefit over standard PETG'],
  },
  'landau-petg-carbon-fibre-1-75mm-1kg': {
    material: 'petg',
    summary: 'Markedly stiffer PETG with a matte finish. Hardened nozzle required.',
    body: [
      'Carbon fibre PETG is substantially more rigid than plain PETG while keeping most of its heat resistance, and it prints with a deep matte surface that hides layer lines well. For brackets and mounts that must not flex under load, it is the strongest combination we stock short of ABS.',
      'It needs a hardened steel nozzle — the fibres are abrasive — and it is more brittle than plain PETG, so it trades some of PETG\'s impact tolerance for stiffness. It also strings less than plain PETG, which is a pleasant surprise for anyone who has fought that.',
    ],
    bestFor: ['Rigid brackets and mounts', 'Parts under sustained load', 'Engineering prototypes'],
    notFor: ['Brass nozzles', 'Parts that need to flex or absorb impact'],
  },
  'landau-abs-1-75mm-1kg': {
    material: 'abs',
    summary: 'Engineering-grade heat and impact resistance. Needs an enclosure and ventilation.',
    body: [
      'ABS softens around 100 °C, which puts it in a different category from PLA and PETG for anything mechanical, automotive, or near a heat source. It absorbs impact by deforming rather than shattering, and it can be drilled and tapped without cracking.',
      'It also vapour-smooths with acetone to a glossy, effectively water-tight surface — a finishing route no other material here offers.',
      'The cost is difficulty. ABS shrinks as it cools, so on an open printer the corners lift and the print fails; an enclosure is not optional above a few centimetres. It emits styrene while printing, so ventilate the space.',
    ],
    bestFor: ['Automotive and engine-bay parts', 'Anything near a heat source', 'Parts to be drilled, tapped or acetone-smoothed'],
    notFor: ['Open-frame printers without an enclosure', 'Unventilated rooms', 'Outdoor use — it yellows in UV; use ASA'],
  },
  'landau-abs-hyper-1-75mm-1kg': {
    material: 'abs',
    summary: 'ABS formulated for higher speeds, and somewhat easier to get clean.',
    body: [
      'Hyper ABS flows more consistently than standard ABS, which makes it both faster to print and a little more forgiving — the consistency helps as much with print quality as with speed.',
      'It does not remove the need for an enclosure or ventilation. Everything true of standard ABS about warping and styrene is still true here.',
    ],
    bestFor: ['Faster ABS printing on a capable machine', 'Anyone finding standard ABS finicky'],
    notFor: ['Printing without an enclosure', 'Outdoor parts'],
  },
  'landau-abs-carbon-fibre-1-75mm-1kg': {
    material: 'abs',
    summary: 'The easiest ABS to print large parts in — the fibres restrain the warping.',
    body: [
      'Carbon fibre ABS is stiffer than plain ABS and, more usefully, warps noticeably less: the chopped fibres restrain the shrinkage that makes large ABS prints lift off the bed. That makes it the ABS to choose for a big footprint.',
      'It needs a hardened nozzle, and it is more brittle than plain ABS — the usual stiffness-for-toughness trade. It still wants an enclosure and ventilation.',
    ],
    bestFor: ['Large ABS parts that would otherwise warp', 'Rigid engineering components'],
    notFor: ['Brass nozzles', 'Parts needing ABS-level impact tolerance'],
  },
  'landau-asa-1-75mm-1kg': {
    material: 'asa',
    summary: 'ABS that survives the weather. The right choice for anything outdoors.',
    body: [
      'ASA was developed as a UV-stable replacement for ABS, and it is why garden furniture, wing mirrors and outdoor signage survive years of sunlight without going chalky. If a printed part will live outside, this is the material — no other filament we stock will hold up.',
      'Mechanically it is near-identical to ABS: similar heat resistance, similar toughness, drills and taps the same way. Think of it as ABS with the UV weakness removed and a small premium added. It also warps slightly less in practice, which makes large parts a little easier despite the same settings.',
      'It needs the same care as ABS: an enclosure, no part cooling, and a ventilated space. More than any other material here, it punishes a draughty workshop.',
    ],
    bestFor: ['Outdoor fittings and garden hardware', 'Anything in direct or through-glass sunlight', 'Automotive exterior parts'],
    notFor: ['Indoor parts where ABS would do for less', 'Printing in a cold or draughty room'],
  },
  'landau-tpu-95a-1-75mm-1kg': {
    material: 'tpu',
    summary: 'Flexible 95A. Firm enough to print reliably, soft enough to be obviously rubbery.',
    body: [
      'TPU at 95A shore hardness is the general-purpose flexible: gaskets and seals, phone and tool cases, vibration-damping feet, grips, and small wheels or tyres. It is also extremely abrasion-resistant and effectively unbreakable — it deforms rather than shattering.',
      'Print it slowly. 20 mm/s solves most TPU problems on its own; push the speed and the filament buckles between the drive gear and the nozzle instead of being pushed forward. Reduce or disable retraction, and dry the spool if it has been open — TPU absorbs moisture faster than anything else here.',
      'A direct-drive extruder makes this easy. On a Bowden machine it is possible but becomes a project.',
    ],
    bestFor: ['Gaskets, seals and damping feet', 'Cases and protective corners', 'Grips and handle covers'],
    notFor: ['Bowden printers, realistically', 'Fast printing', 'Parts needing dimensional precision'],
  },
  'landau-tpu-pro-1-75mm-1kg': {
    material: 'tpu',
    summary: 'TPU with tighter diameter tolerance — which matters more here than elsewhere.',
    body: [
      'Diameter consistency matters more in a flexible filament than in a rigid one. A thin spot lets the filament buckle in the extruder instead of feeding, and a thick spot jams it — both show up as under-extrusion partway through a long print.',
      'If you have fought inconsistent TPU extrusion, this is the range that removes the filament from the list of suspects. Everything else about printing it — slow, minimal retraction, dry the spool, direct drive if you can — is unchanged.',
    ],
    bestFor: ['Long flexible prints that must not fail partway', 'Bowden setups, where consistency helps most', 'Production runs'],
    notFor: ['Casual prints where standard 95A is already working'],
  },
};

export function rangeCopyFor(slug: string | null | undefined): RangeCopy | undefined {
  return slug ? RANGE_COPY[slug] : undefined;
}
