/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSuppliersIndexRouteImport } from './routes/_authed/suppliers/index'
import { Route as AuthedSupplierInvoicesIndexRouteImport } from './routes/_authed/supplier-invoices/index'
import { Route as AuthedStockIndexRouteImport } from './routes/_authed/stock/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedPurchaseOrdersIndexRouteImport } from './routes/_authed/purchase-orders/index'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed/products/index'
import { Route as AuthedOrdersIndexRouteImport } from './routes/_authed/orders/index'
import { Route as AuthedInvoicesIndexRouteImport } from './routes/_authed/invoices/index'
import { Route as AuthedIntegrationsIndexRouteImport } from './routes/_authed/integrations/index'
import { Route as AuthedCustomersIndexRouteImport } from './routes/_authed/customers/index'
import { Route as AuthedSuppliersNewRouteImport } from './routes/_authed/suppliers/new'
import { Route as AuthedSuppliersIdRouteImport } from './routes/_authed/suppliers/$id'
import { Route as AuthedSupplierInvoicesIdRouteImport } from './routes/_authed/supplier-invoices/$id'
import { Route as AuthedStockTransferRouteImport } from './routes/_authed/stock/transfer'
import { Route as AuthedStockSerialRouteImport } from './routes/_authed/stock/serial'
import { Route as AuthedStockReportRouteImport } from './routes/_authed/stock/report'
import { Route as AuthedStockAdjustRouteImport } from './routes/_authed/stock/adjust'
import { Route as AuthedPurchaseOrdersNewRouteImport } from './routes/_authed/purchase-orders/new'
import { Route as AuthedPurchaseOrdersIdRouteImport } from './routes/_authed/purchase-orders/$id'
import { Route as AuthedProductsNewRouteImport } from './routes/_authed/products/new'
import { Route as AuthedProductsIdRouteImport } from './routes/_authed/products/$id'
import { Route as AuthedOrdersNewRouteImport } from './routes/_authed/orders/new'
import { Route as AuthedOrdersIdRouteImport } from './routes/_authed/orders/$id'
import { Route as AuthedInvoicesIdRouteImport } from './routes/_authed/invoices/$id'
import { Route as AuthedIntegrationsMarketplaceRouteImport } from './routes/_authed/integrations/marketplace'
import { Route as AuthedIntegrationsCsvRouteImport } from './routes/_authed/integrations/csv'
import { Route as AuthedIntegrationsBulkRouteImport } from './routes/_authed/integrations/bulk'
import { Route as AuthedCustomersNewRouteImport } from './routes/_authed/customers/new'
import { Route as AuthedCustomersIdRouteImport } from './routes/_authed/customers/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSuppliersIndexRoute = AuthedSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSupplierInvoicesIndexRoute =
  AuthedSupplierInvoicesIndexRouteImport.update({
    id: '/supplier-invoices/',
    path: '/supplier-invoices/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedStockIndexRoute = AuthedStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPurchaseOrdersIndexRoute =
  AuthedPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrdersIndexRoute = AuthedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedInvoicesIndexRoute = AuthedInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedIntegrationsIndexRoute = AuthedIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCustomersIndexRoute = AuthedCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSuppliersNewRoute = AuthedSuppliersNewRouteImport.update({
  id: '/suppliers/new',
  path: '/suppliers/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSuppliersIdRoute = AuthedSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSupplierInvoicesIdRoute =
  AuthedSupplierInvoicesIdRouteImport.update({
    id: '/supplier-invoices/$id',
    path: '/supplier-invoices/$id',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedStockTransferRoute = AuthedStockTransferRouteImport.update({
  id: '/stock/transfer',
  path: '/stock/transfer',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedStockSerialRoute = AuthedStockSerialRouteImport.update({
  id: '/stock/serial',
  path: '/stock/serial',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedStockReportRoute = AuthedStockReportRouteImport.update({
  id: '/stock/report',
  path: '/stock/report',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedStockAdjustRoute = AuthedStockAdjustRouteImport.update({
  id: '/stock/adjust',
  path: '/stock/adjust',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPurchaseOrdersNewRoute = AuthedPurchaseOrdersNewRouteImport.update({
  id: '/purchase-orders/new',
  path: '/purchase-orders/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPurchaseOrdersIdRoute = AuthedPurchaseOrdersIdRouteImport.update({
  id: '/purchase-orders/$id',
  path: '/purchase-orders/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProductsNewRoute = AuthedProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProductsIdRoute = AuthedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrdersNewRoute = AuthedOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrdersIdRoute = AuthedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedInvoicesIdRoute = AuthedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedIntegrationsMarketplaceRoute =
  AuthedIntegrationsMarketplaceRouteImport.update({
    id: '/integrations/marketplace',
    path: '/integrations/marketplace',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedIntegrationsCsvRoute = AuthedIntegrationsCsvRouteImport.update({
  id: '/integrations/csv',
  path: '/integrations/csv',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedIntegrationsBulkRoute = AuthedIntegrationsBulkRouteImport.update({
  id: '/integrations/bulk',
  path: '/integrations/bulk',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCustomersNewRoute = AuthedCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCustomersIdRoute = AuthedCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/customers/$id': typeof AuthedCustomersIdRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/integrations/bulk': typeof AuthedIntegrationsBulkRoute
  '/integrations/csv': typeof AuthedIntegrationsCsvRoute
  '/integrations/marketplace': typeof AuthedIntegrationsMarketplaceRoute
  '/invoices/$id': typeof AuthedInvoicesIdRoute
  '/orders/$id': typeof AuthedOrdersIdRoute
  '/orders/new': typeof AuthedOrdersNewRoute
  '/products/$id': typeof AuthedProductsIdRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/purchase-orders/$id': typeof AuthedPurchaseOrdersIdRoute
  '/purchase-orders/new': typeof AuthedPurchaseOrdersNewRoute
  '/stock/adjust': typeof AuthedStockAdjustRoute
  '/stock/report': typeof AuthedStockReportRoute
  '/stock/serial': typeof AuthedStockSerialRoute
  '/stock/transfer': typeof AuthedStockTransferRoute
  '/supplier-invoices/$id': typeof AuthedSupplierInvoicesIdRoute
  '/suppliers/$id': typeof AuthedSuppliersIdRoute
  '/suppliers/new': typeof AuthedSuppliersNewRoute
  '/customers/': typeof AuthedCustomersIndexRoute
  '/integrations/': typeof AuthedIntegrationsIndexRoute
  '/invoices/': typeof AuthedInvoicesIndexRoute
  '/orders/': typeof AuthedOrdersIndexRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/purchase-orders/': typeof AuthedPurchaseOrdersIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/stock/': typeof AuthedStockIndexRoute
  '/supplier-invoices/': typeof AuthedSupplierInvoicesIndexRoute
  '/suppliers/': typeof AuthedSuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedIndexRoute
  '/customers/$id': typeof AuthedCustomersIdRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/integrations/bulk': typeof AuthedIntegrationsBulkRoute
  '/integrations/csv': typeof AuthedIntegrationsCsvRoute
  '/integrations/marketplace': typeof AuthedIntegrationsMarketplaceRoute
  '/invoices/$id': typeof AuthedInvoicesIdRoute
  '/orders/$id': typeof AuthedOrdersIdRoute
  '/orders/new': typeof AuthedOrdersNewRoute
  '/products/$id': typeof AuthedProductsIdRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/purchase-orders/$id': typeof AuthedPurchaseOrdersIdRoute
  '/purchase-orders/new': typeof AuthedPurchaseOrdersNewRoute
  '/stock/adjust': typeof AuthedStockAdjustRoute
  '/stock/report': typeof AuthedStockReportRoute
  '/stock/serial': typeof AuthedStockSerialRoute
  '/stock/transfer': typeof AuthedStockTransferRoute
  '/supplier-invoices/$id': typeof AuthedSupplierInvoicesIdRoute
  '/suppliers/$id': typeof AuthedSuppliersIdRoute
  '/suppliers/new': typeof AuthedSuppliersNewRoute
  '/customers': typeof AuthedCustomersIndexRoute
  '/integrations': typeof AuthedIntegrationsIndexRoute
  '/invoices': typeof AuthedInvoicesIndexRoute
  '/orders': typeof AuthedOrdersIndexRoute
  '/products': typeof AuthedProductsIndexRoute
  '/purchase-orders': typeof AuthedPurchaseOrdersIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/stock': typeof AuthedStockIndexRoute
  '/supplier-invoices': typeof AuthedSupplierInvoicesIndexRoute
  '/suppliers': typeof AuthedSuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/customers/$id': typeof AuthedCustomersIdRoute
  '/_authed/customers/new': typeof AuthedCustomersNewRoute
  '/_authed/integrations/bulk': typeof AuthedIntegrationsBulkRoute
  '/_authed/integrations/csv': typeof AuthedIntegrationsCsvRoute
  '/_authed/integrations/marketplace': typeof AuthedIntegrationsMarketplaceRoute
  '/_authed/invoices/$id': typeof AuthedInvoicesIdRoute
  '/_authed/orders/$id': typeof AuthedOrdersIdRoute
  '/_authed/orders/new': typeof AuthedOrdersNewRoute
  '/_authed/products/$id': typeof AuthedProductsIdRoute
  '/_authed/products/new': typeof AuthedProductsNewRoute
  '/_authed/purchase-orders/$id': typeof AuthedPurchaseOrdersIdRoute
  '/_authed/purchase-orders/new': typeof AuthedPurchaseOrdersNewRoute
  '/_authed/stock/adjust': typeof AuthedStockAdjustRoute
  '/_authed/stock/report': typeof AuthedStockReportRoute
  '/_authed/stock/serial': typeof AuthedStockSerialRoute
  '/_authed/stock/transfer': typeof AuthedStockTransferRoute
  '/_authed/supplier-invoices/$id': typeof AuthedSupplierInvoicesIdRoute
  '/_authed/suppliers/$id': typeof AuthedSuppliersIdRoute
  '/_authed/suppliers/new': typeof AuthedSuppliersNewRoute
  '/_authed/customers/': typeof AuthedCustomersIndexRoute
  '/_authed/integrations/': typeof AuthedIntegrationsIndexRoute
  '/_authed/invoices/': typeof AuthedInvoicesIndexRoute
  '/_authed/orders/': typeof AuthedOrdersIndexRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/purchase-orders/': typeof AuthedPurchaseOrdersIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/stock/': typeof AuthedStockIndexRoute
  '/_authed/supplier-invoices/': typeof AuthedSupplierInvoicesIndexRoute
  '/_authed/suppliers/': typeof AuthedSuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customers/$id'
    | '/customers/new'
    | '/integrations/bulk'
    | '/integrations/csv'
    | '/integrations/marketplace'
    | '/invoices/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/products/$id'
    | '/products/new'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/stock/adjust'
    | '/stock/report'
    | '/stock/serial'
    | '/stock/transfer'
    | '/supplier-invoices/$id'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/customers/'
    | '/integrations/'
    | '/invoices/'
    | '/orders/'
    | '/products/'
    | '/purchase-orders/'
    | '/settings/'
    | '/stock/'
    | '/supplier-invoices/'
    | '/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/customers/$id'
    | '/customers/new'
    | '/integrations/bulk'
    | '/integrations/csv'
    | '/integrations/marketplace'
    | '/invoices/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/products/$id'
    | '/products/new'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/stock/adjust'
    | '/stock/report'
    | '/stock/serial'
    | '/stock/transfer'
    | '/supplier-invoices/$id'
    | '/suppliers/$id'
    | '/suppliers/new'
    | '/customers'
    | '/integrations'
    | '/invoices'
    | '/orders'
    | '/products'
    | '/purchase-orders'
    | '/settings'
    | '/stock'
    | '/supplier-invoices'
    | '/suppliers'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/'
    | '/_authed/customers/$id'
    | '/_authed/customers/new'
    | '/_authed/integrations/bulk'
    | '/_authed/integrations/csv'
    | '/_authed/integrations/marketplace'
    | '/_authed/invoices/$id'
    | '/_authed/orders/$id'
    | '/_authed/orders/new'
    | '/_authed/products/$id'
    | '/_authed/products/new'
    | '/_authed/purchase-orders/$id'
    | '/_authed/purchase-orders/new'
    | '/_authed/stock/adjust'
    | '/_authed/stock/report'
    | '/_authed/stock/serial'
    | '/_authed/stock/transfer'
    | '/_authed/supplier-invoices/$id'
    | '/_authed/suppliers/$id'
    | '/_authed/suppliers/new'
    | '/_authed/customers/'
    | '/_authed/integrations/'
    | '/_authed/invoices/'
    | '/_authed/orders/'
    | '/_authed/products/'
    | '/_authed/purchase-orders/'
    | '/_authed/settings/'
    | '/_authed/stock/'
    | '/_authed/supplier-invoices/'
    | '/_authed/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/suppliers/': {
      id: '/_authed/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthedSuppliersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/supplier-invoices/': {
      id: '/_authed/supplier-invoices/'
      path: '/supplier-invoices'
      fullPath: '/supplier-invoices/'
      preLoaderRoute: typeof AuthedSupplierInvoicesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/stock/': {
      id: '/_authed/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof AuthedStockIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/purchase-orders/': {
      id: '/_authed/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AuthedPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/': {
      id: '/_authed/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthedOrdersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/invoices/': {
      id: '/_authed/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthedInvoicesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/integrations/': {
      id: '/_authed/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AuthedIntegrationsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/customers/': {
      id: '/_authed/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthedCustomersIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/suppliers/new': {
      id: '/_authed/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof AuthedSuppliersNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/suppliers/$id': {
      id: '/_authed/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AuthedSuppliersIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/supplier-invoices/$id': {
      id: '/_authed/supplier-invoices/$id'
      path: '/supplier-invoices/$id'
      fullPath: '/supplier-invoices/$id'
      preLoaderRoute: typeof AuthedSupplierInvoicesIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/stock/transfer': {
      id: '/_authed/stock/transfer'
      path: '/stock/transfer'
      fullPath: '/stock/transfer'
      preLoaderRoute: typeof AuthedStockTransferRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/stock/serial': {
      id: '/_authed/stock/serial'
      path: '/stock/serial'
      fullPath: '/stock/serial'
      preLoaderRoute: typeof AuthedStockSerialRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/stock/report': {
      id: '/_authed/stock/report'
      path: '/stock/report'
      fullPath: '/stock/report'
      preLoaderRoute: typeof AuthedStockReportRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/stock/adjust': {
      id: '/_authed/stock/adjust'
      path: '/stock/adjust'
      fullPath: '/stock/adjust'
      preLoaderRoute: typeof AuthedStockAdjustRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/purchase-orders/new': {
      id: '/_authed/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof AuthedPurchaseOrdersNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/purchase-orders/$id': {
      id: '/_authed/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AuthedPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/new': {
      id: '/_authed/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthedProductsNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/products/$id': {
      id: '/_authed/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthedProductsIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/new': {
      id: '/_authed/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthedOrdersNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orders/$id': {
      id: '/_authed/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthedOrdersIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/invoices/$id': {
      id: '/_authed/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthedInvoicesIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/integrations/marketplace': {
      id: '/_authed/integrations/marketplace'
      path: '/integrations/marketplace'
      fullPath: '/integrations/marketplace'
      preLoaderRoute: typeof AuthedIntegrationsMarketplaceRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/integrations/csv': {
      id: '/_authed/integrations/csv'
      path: '/integrations/csv'
      fullPath: '/integrations/csv'
      preLoaderRoute: typeof AuthedIntegrationsCsvRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/integrations/bulk': {
      id: '/_authed/integrations/bulk'
      path: '/integrations/bulk'
      fullPath: '/integrations/bulk'
      preLoaderRoute: typeof AuthedIntegrationsBulkRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/customers/new': {
      id: '/_authed/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthedCustomersNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/customers/$id': {
      id: '/_authed/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthedCustomersIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCustomersIdRoute: typeof AuthedCustomersIdRoute
  AuthedCustomersNewRoute: typeof AuthedCustomersNewRoute
  AuthedIntegrationsBulkRoute: typeof AuthedIntegrationsBulkRoute
  AuthedIntegrationsCsvRoute: typeof AuthedIntegrationsCsvRoute
  AuthedIntegrationsMarketplaceRoute: typeof AuthedIntegrationsMarketplaceRoute
  AuthedInvoicesIdRoute: typeof AuthedInvoicesIdRoute
  AuthedOrdersIdRoute: typeof AuthedOrdersIdRoute
  AuthedOrdersNewRoute: typeof AuthedOrdersNewRoute
  AuthedProductsIdRoute: typeof AuthedProductsIdRoute
  AuthedProductsNewRoute: typeof AuthedProductsNewRoute
  AuthedPurchaseOrdersIdRoute: typeof AuthedPurchaseOrdersIdRoute
  AuthedPurchaseOrdersNewRoute: typeof AuthedPurchaseOrdersNewRoute
  AuthedStockAdjustRoute: typeof AuthedStockAdjustRoute
  AuthedStockReportRoute: typeof AuthedStockReportRoute
  AuthedStockSerialRoute: typeof AuthedStockSerialRoute
  AuthedStockTransferRoute: typeof AuthedStockTransferRoute
  AuthedSupplierInvoicesIdRoute: typeof AuthedSupplierInvoicesIdRoute
  AuthedSuppliersIdRoute: typeof AuthedSuppliersIdRoute
  AuthedSuppliersNewRoute: typeof AuthedSuppliersNewRoute
  AuthedCustomersIndexRoute: typeof AuthedCustomersIndexRoute
  AuthedIntegrationsIndexRoute: typeof AuthedIntegrationsIndexRoute
  AuthedInvoicesIndexRoute: typeof AuthedInvoicesIndexRoute
  AuthedOrdersIndexRoute: typeof AuthedOrdersIndexRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedPurchaseOrdersIndexRoute: typeof AuthedPurchaseOrdersIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedStockIndexRoute: typeof AuthedStockIndexRoute
  AuthedSupplierInvoicesIndexRoute: typeof AuthedSupplierInvoicesIndexRoute
  AuthedSuppliersIndexRoute: typeof AuthedSuppliersIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCustomersIdRoute: AuthedCustomersIdRoute,
  AuthedCustomersNewRoute: AuthedCustomersNewRoute,
  AuthedIntegrationsBulkRoute: AuthedIntegrationsBulkRoute,
  AuthedIntegrationsCsvRoute: AuthedIntegrationsCsvRoute,
  AuthedIntegrationsMarketplaceRoute: AuthedIntegrationsMarketplaceRoute,
  AuthedInvoicesIdRoute: AuthedInvoicesIdRoute,
  AuthedOrdersIdRoute: AuthedOrdersIdRoute,
  AuthedOrdersNewRoute: AuthedOrdersNewRoute,
  AuthedProductsIdRoute: AuthedProductsIdRoute,
  AuthedProductsNewRoute: AuthedProductsNewRoute,
  AuthedPurchaseOrdersIdRoute: AuthedPurchaseOrdersIdRoute,
  AuthedPurchaseOrdersNewRoute: AuthedPurchaseOrdersNewRoute,
  AuthedStockAdjustRoute: AuthedStockAdjustRoute,
  AuthedStockReportRoute: AuthedStockReportRoute,
  AuthedStockSerialRoute: AuthedStockSerialRoute,
  AuthedStockTransferRoute: AuthedStockTransferRoute,
  AuthedSupplierInvoicesIdRoute: AuthedSupplierInvoicesIdRoute,
  AuthedSuppliersIdRoute: AuthedSuppliersIdRoute,
  AuthedSuppliersNewRoute: AuthedSuppliersNewRoute,
  AuthedCustomersIndexRoute: AuthedCustomersIndexRoute,
  AuthedIntegrationsIndexRoute: AuthedIntegrationsIndexRoute,
  AuthedInvoicesIndexRoute: AuthedInvoicesIndexRoute,
  AuthedOrdersIndexRoute: AuthedOrdersIndexRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedPurchaseOrdersIndexRoute: AuthedPurchaseOrdersIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedStockIndexRoute: AuthedStockIndexRoute,
  AuthedSupplierInvoicesIndexRoute: AuthedSupplierInvoicesIndexRoute,
  AuthedSuppliersIndexRoute: AuthedSuppliersIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
