/**
 * Email + password login.
 *
 *   POST /api/v1/auth/login   { email, password }
 *     200 → { token, user }
 *     401 → { error: 'invalid_credentials' }
 *
 * The JWT issued here matches the previous "paste a JWT generated by
 * generate-test-token.ts" flow byte-for-byte: payload shape is
 * `{ userId, companyId, email, roles }` signed with `JWT_SECRET`,
 * 30 days expiry. Every existing route that consumes a JWT continues
 * to work; only the issuance mechanism has changed.
 *
 * Failure responses use the same generic message regardless of whether
 * the email exists or the password is wrong, so the endpoint can't be
 * used for email enumeration.
 */
import { and, eq, isNull } from 'drizzle-orm';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { getDb } from '../../config/database.js';
import { users } from '../../db/schema/index.js';
import { verifyPassword } from '../../shared/auth/password.js';

const loginBodySchema = z.object({
  email: z.string().email().max(320),
  password: z.string().min(1).max(500),
});

const INVALID = { success: false, error: 'invalid_credentials' } as const;

export async function authRoutes(app: FastifyInstance) {
  app.post('/auth/login', async (request, reply) => {
    const parsed = loginBodySchema.safeParse(request.body);
    if (!parsed.success) {
      return reply.status(400).send({ success: false, error: 'invalid_request' });
    }
    const { email, password } = parsed.data;

    const db = getDb();
    const row = await db.query.users.findFirst({
      where: and(eq(users.email, email.toLowerCase()), isNull(users.deletedAt)),
    });
    if (!row) {
      return reply.status(401).send(INVALID);
    }

    const ok = await verifyPassword(password, row.passwordHash);
    if (!ok) {
      return reply.status(401).send(INVALID);
    }

    const token = app.jwt.sign(
      {
        userId: row.id,
        companyId: row.companyId,
        email: row.email,
        roles: row.roles,
      },
      { expiresIn: '30d' },
    );

    // Best-effort lastLoginAt refresh; failure here mustn't fail the login.
    void db
      .update(users)
      .set({ lastLoginAt: new Date(), updatedAt: new Date() })
      .where(eq(users.id, row.id))
      .catch((err) => {
        request.log.warn({ err, userId: row.id }, 'Failed to update users.last_login_at');
      });

    return reply.send({
      success: true,
      data: {
        token,
        user: {
          id: row.id,
          email: row.email,
          name: row.name,
          roles: row.roles,
        },
      },
    });
  });
}
